<?php
/**
*
* common [Norwegian Bokmaal]
*
* @package language
* @version $Id$
* @author Morten R. N. http://www.morten.com
* @copyright (c) 2009 phpBB Group, 2011 Norwegian translation team, Morten R. N.
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> 'Norwegian translation by Morten R. N.',
	'DIRECTION'			=> 'ltr',
	'DATE_FORMAT'		=> '|j. M Y|',	// 1. jan 2007 (med relative dager aktiveret)
	'USER_LANG'			=> 'no-nb',

	'1_DAY'			=> '1 dag',
	'1_MONTH'		=> '1 måned',
	'1_YEAR'		=> '1 år',
	'2_WEEKS'		=> '2 uker',
	'3_MONTHS'		=> '3 måneder',
	'6_MONTHS'		=> '6 måneder',
	'7_DAYS'		=> '7 dager',

	'ACCOUNT_ALREADY_ACTIVATED'		=> 'Bruker kontoen din er allerede aktivert.',
	'ACCOUNT_DEACTIVATED'			=> 'Bruker kontoen din er manuelt deaktivert og kan kun aktiveres av en administrator.',
	'ACCOUNT_NOT_ACTIVATED'			=> 'Bruker kontoen din er ikke aktivert enda.',
	'ACP'							=> 'Administrasjons Panel',
	'ACTIVE'						=> 'aktiv',
	'ACTIVE_ERROR'					=> 'Det spesifiserte brukernavnet er i øyeblikket ikke aktivt. Hvis du har problemer med å aktivere brukeren din, vennligst kontakt en administrator.',
	'ADMINISTRATOR'					=> 'Administrator',
	'ADMINISTRATORS'				=> 'Administratorer',
	'AGE'							=> 'Alder',
	'AIM'							=> 'AIM',
	'ALLOWED'						=> 'Tillatt',
	'ALL_FILES'						=> 'Alle filer',
	'ALL_FORUMS'					=> 'Alle forum',
	'ALL_MESSAGES'					=> 'Alle meldinger',
	'ALL_POSTS'						=> 'Alle meldinger',
	'ALL_TIMES'						=> 'Alle tider er %1$s %2$s',
	'ALL_TOPICS'					=> 'Alle emner',
	'AND'							=> 'og',
	'ARE_WATCHING_FORUM'			=> 'Du abonnerer på dette forumet og vil få meldinger om nye innlegg.',
	'ARE_WATCHING_TOPIC'			=> 'Du abonnerer på dette emnet og vil få meldinger om nye innlegg.',
	'ASCENDING'						=> 'Stigende',
	'ATTACHMENTS'					=> 'Vedlegg',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> 'Bilde du prøvde å legge ved er ikke en gyldig bildefil.',
	'AUTHOR'						=> 'Forfatter',
	'AUTH_NO_PROFILE_CREATED'		=> 'Feil under opprettelse av brukerprofil.',
	'AVATAR_DISALLOWED_CONTENT'		=> 'Opplastingen ble avvist fordi den opplastede filen ble identifisert som et mulig angreps forsøk.',
	'AVATAR_DISALLOWED_EXTENSION'	=> 'Filen kan ikke vises da filtypen <strong>%s</strong> ikke er tillatt.',
	'AVATAR_EMPTY_REMOTE_DATA'		=> 'Avataren ble ikke lastet opp da den ser ut til å være ugyldig eller skadet.',
	'AVATAR_EMPTY_FILEUPLOAD'		=> 'Den opplastede avatar filen er tom.',
	'AVATAR_INVALID_FILENAME'		=> '%s er et ugyldig filnavn.',
	'AVATAR_NOT_UPLOADED'			=> 'Avataren kunne ikke lastes opp.',
	'AVATAR_NO_SIZE'				=> 'Bredden eller høyden på den linkede avataren kunne ikke avgjøres. Vennligst legg det inn manuelt.',
	'AVATAR_PARTIAL_UPLOAD'			=> 'Den spesifiserte filen ble bare delvis lastet opp.',
	'AVATAR_PHP_SIZE_NA'			=> 'Avatarens fil størrelse er for stor.<br />Kunne ikke fastslå maksimal tillatt størrelse definert i php.ini.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> 'Avatarens fil størrelse er for stor. Maksimal filstørrelse er %1$d %2$s.<br />Dette er fastsatt i php.ini og kan ikke overskrides.',
	'AVATAR_URL_INVALID'			=> 'URLen du skrev inn er ugyldig.',
	'AVATAR_URL_NOT_FOUND'			=> 'Kan ikke finne den spesifiserte filen.',
	'AVATAR_WRONG_FILESIZE'			=> 'Avatarens filstørrelse må være mellom 0 og %1d %2s.',
	'AVATAR_WRONG_SIZE'				=> 'Den valgte avataren er %5$d piksler bred og %6$d piksler høy. Den skal være minst %1$d piksler bred, %2$d piksler høy og maksimalt %3$d piksler bred og %4$d piksler høy.',

	'BACK_TO_TOP'			=> 'Topp',
	'BACK_TO_PREV'			=> 'Tilbake til forrige side',
	'BAN_TRIGGERED_BY_EMAIL'=> 'Din e-post adresse er utestengt.',
	'BAN_TRIGGERED_BY_IP'	=> 'Din IP adresse er utestengt.',
	'BAN_TRIGGERED_BY_USER'	=> 'Ditt brukernavn er utestengt.',
	'BBCODE_GUIDE'			=> 'BBkode-guide',
	'BCC'					=> 'BCC',
	'BIRTHDAYS'				=> 'Fødselsdager',
	'BOARD_BAN_PERM'		=> 'Du har blitt <strong>permanent</strong> utestengt fra dette forumet.<br /><br />Vennligst kontakt %2$sforum administrator%3$s for mer informasjon.',
	'BOARD_BAN_REASON'		=> 'Årsak til utestengelse: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> 'Du har blitt utestengt fra dette forumet inntil <strong>%1$s</strong>.<br /><br />Vennligst kontakt %2$sforum administrator%3$s for mer informasjon.',
	'BOARD_DISABLE'			=> 'Beklager, dette forumet er for øyeblikket ikke tilgjengelig.',
	'BOARD_DISABLED'		=> 'Beklager, forumet er for øyeblikket ikke tilgjengelig.',
	'BOARD_UNAVAILABLE'		=> 'Beklager, forumet er midlertidig ikke tilgjengelig, vennligst prøv igjen om en liten stund.',
	'BROWSING_FORUM'		=> 'Brukere som leser dette forumet: %1$s',
	'BROWSING_FORUM_GUEST'	=> 'Brukere som leser dette forumet: %1$s og %2$d gjest',
	'BROWSING_FORUM_GUESTS'	=> 'Brukere som leser dette forumet: %1$s og %2$d gjester',
	'BYTES'					=> 'Bytes',

	'CANCEL'				=> 'Avbryt',
	'CHANGE'				=> 'Endre',
	'CHANGE_FONT_SIZE'		=> 'Endre skriftstørrelse',
	'CHANGING_PREFERENCES'	=> 'Endre foruminnstillinger',
	'CHANGING_PROFILE'		=> 'Endre profilinnstillinger',
	'CLICK_VIEW_PRIVMSG'	=> '%sTilbake til din innboks%s',
	'COLLAPSE_VIEW'			=> 'Skjul visning',
	'CLOSE_WINDOW'			=> 'Lukk vindu',
	'COLOUR_SWATCH'			=> 'Fargevelger',
	'COMMA_SEPARATOR'		=> ', ',	// Used in pagination of ACP & prosilver, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'				=> 'Bekreft',
	'CONFIRM_CODE'			=> 'Bekreftelseskode',
	'CONFIRM_CODE_EXPLAIN'	=> 'Skriv inn koden eksakt som du ser den på bildet. Om du bruker små eller store bokstaver spiller ingen rolle.',
	'CONFIRM_CODE_WRONG'	=> 'Bekreftelseskoden du skrev inn er feil.',
	'CONFIRM_OPERATION'		=> 'Er du sikker på at du ønsker at utføre denne handling?',
	'CONGRATULATIONS'		=> 'Gratulerer',
	'CONNECTION_FAILED'		=> 'Tilkobling mislyktes.',
	'CONNECTION_SUCCESS'	=> 'Tilkoblingen var vellykket!',
	'COOKIES_DELETED'		=> 'Alle forumets informasjonskapsler er slettet.',
	'CURRENT_TIME'			=> 'Dato og klokkeslett er %s',

	'DAY'					=> 'Dag',
	'DAYS'					=> 'Dager',
	'DELETE'				=> 'Slett',
	'DELETE_ALL'			=> 'Slett alle',
	'DELETE_COOKIES'		=> 'Slett alle forumets informasjonskapsler',
	'DELETE_MARKED'			=> 'Slett valgte',
	'DELETE_POST'			=> 'Slett innlegg',
	'DELIMITER'				=> 'Separator',
	'DESCENDING'			=> 'Synkende',
	'DISABLED'				=> 'Innaktiv',
	'DISPLAY'				=> 'Vis',
	'DISPLAY_GUESTS'		=> 'Vis gjester',
	'DISPLAY_MESSAGES'		=> 'Vis meldinger fra forrige',
	'DISPLAY_POSTS'			=> 'Vis innlegg fra forrige',
	'DISPLAY_TOPICS'		=> 'Vis emner fra forrige',
	'DOWNLOADED'			=> 'Nedlastet',
	'DOWNLOADING_FILE'		=> 'Laster ned fil',
	'DOWNLOAD_COUNT'		=> 'Nedlastet %d gang',
	'DOWNLOAD_COUNTS'		=> 'Nedlastet %d ganger',
	'DOWNLOAD_COUNT_NONE'	=> 'Ikke nedlastet enda',
	'VIEWED_COUNT'			=> 'Vist %d gang',
	'VIEWED_COUNTS'			=> 'Vist %d ganger',
	'VIEWED_COUNT_NONE'		=> 'Ikke vist enda',

	'EDIT_POST'							=> 'Rediger innlegg',
	'EMAIL'								=> 'E-post', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'						=> 'E-post adresse',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> 'Problemer oppstod ved sending av e-post i <strong>Linje %1$s</strong>. Svar: %2$s.',
	'EMPTY_SUBJECT'						=> 'Du må angi en tittel når du skriver et nytt emne.',
	'EMPTY_MESSAGE_SUBJECT'				=> 'Du må angi en tittel når du skriver en ny melding.',
	'ENABLED'							=> 'Aktiv',
	'ENCLOSURE'							=> 'Vedlegg',
	'ERR_CHANGING_DIRECTORY'			=> 'Kunne ikke skifte mappe.',
	'ERR_CONNECTING_SERVER'				=> 'Feil ved tilkobling til server.',
	'ERR_JAB_AUTH'						=> 'Kunne ikke autorisere på Jabber-server.',
	'ERR_JAB_CONNECT'					=> 'Kunne ikke koble til Jabber-server.',
	'ERR_UNABLE_TO_LOGIN'				=> 'Angitt brukernavn eller passord er feil.',
	'ERR_UNWATCHING'					=> 'Det oppstod en feil ved deaktivering av abonnementet.',
	'ERR_WATCHING'						=> 'Det oppstod en feil ved aktivering av abonnementet.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> 'Den angitte phpBB stien ser ut til å være ugyldig.',
	'EXPAND_VIEW'						=> 'Utvid visning',
	'EXTENSION'							=> 'Filtype',
	'EXTENSION_DISABLED_AFTER_POSTING'	=> 'Filtypen <strong>%s</strong> er deaktivert og kan ikke lenger vises.',

	'FAQ'					=> 'OSS',
	'FAQ_EXPLAIN'			=> 'Ofte stilte spørsmål',
	'FILENAME'				=> 'Filnavn',
	'FILESIZE'				=> 'Filstørrelse',
	'FILEDATE'				=> 'Fildato',
	'FILE_COMMENT'			=> 'Filkommentar',
	'FILE_NOT_FOUND'		=> 'Den ønskede filen kunne ikke bli funnet.',
	'FIND_USERNAME'			=> 'Finn et medlem',
	'FOLDER'				=> 'Mappe',
	'FORGOT_PASS'			=> 'Jeg har glemt mitt passord',
	'FORM_INVALID'			=> 'Den innsendte formular var ugyldig. Prøv igjen.',
	'FORUM'					=> 'Forum',
	'FORUMS'				=> 'Forum',
	'FORUMS_MARKED'			=> 'De valgte forumene har blitt markert som lest.',
	'FORUM_CAT'				=> 'Forumkategori',
	'FORUM_INDEX'			=> 'Forumets hovedside',
	'FORUM_LINK'			=> 'Forumlink',
	'FORUM_LOCATION'		=> 'Forumplassering',
	'FORUM_LOCKED'			=> 'Forum stengt',
	'FORUM_RULES'			=> 'Forumregler',
	'FORUM_RULES_LINK'		=> 'Klikk her for å se forumets regler',
	'FROM'					=> 'fra',
	'FSOCK_DISABLED'		=> 'Handlingen kunne ikke fullføres fordi <var>fsockopen</var> funksjonen er deaktivert, eller fordi den forespurte server ikke ble funnet.',

	'FTP_FSOCK_HOST'				=> 'FTP server',
	'FTP_FSOCK_HOST_EXPLAIN'		=> 'FTP server for tilkobling til din site.',
	'FTP_FSOCK_PASSWORD'			=> 'FTP passord',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'Passord for din FTP bruker.',
	'FTP_FSOCK_PORT'				=> 'FTP-port',
	'FTP_FSOCK_PORT_EXPLAIN'		=> 'Porten som brukes for tilkobling til serveren.',
	'FTP_FSOCK_ROOT_PATH'			=> 'Sti til phpBB',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'Sti fra roten til ditt phpBB forum.',
	'FTP_FSOCK_TIMEOUT'				=> 'FTP timeout',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'		=> 'Antall sekunder systemet vil vente på respons fra serveren.',
	'FTP_FSOCK_USERNAME'			=> 'FTP brukernavn',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'Brukernavnet som brukes for tilkobling til serveren.',

	'FTP_HOST'					=> 'FTP server',
	'FTP_HOST_EXPLAIN'			=> 'FTP server for tilkobling til din site.',
	'FTP_PASSWORD'				=> 'FTP passord',
	'FTP_PASSWORD_EXPLAIN'		=> 'Passord for din FTP bruker.',
	'FTP_PORT'					=> 'FTP-port',
	'FTP_PORT_EXPLAIN'			=> 'Porten som brukes for tilkobling til serveren.',
	'FTP_ROOT_PATH'				=> 'Sti til phpBB',
	'FTP_ROOT_PATH_EXPLAIN'		=> 'Sti fra roten til ditt phpBB forum.',
	'FTP_TIMEOUT'				=> 'FTP timeout',
	'FTP_TIMEOUT_EXPLAIN'		=> 'Antall sekunder systemet vil vente på respons fra serveren.',
	'FTP_USERNAME'				=> 'FTP brukernavn',
	'FTP_USERNAME_EXPLAIN'		=> 'Brukernavnet som brukes for tilkobling til serveren.',

	'GENERAL_ERROR'				=> 'Generell feil',
	'GB'						=> 'GB',
	'GIB'						=> 'GiB',
	'GO'						=> 'Ok',
	'GOTO_PAGE'					=> 'Gåtil side',
	'GROUP'						=> 'Gruppe',
	'GROUPS'					=> 'Grupper',
	'GROUP_ERR_TYPE'			=> 'Upassende gruppetype valgt.',
	'GROUP_ERR_USERNAME'		=> 'Gruppenavn ikke oppgitt.',
	'GROUP_ERR_USER_LONG'		=> 'Gruppenavn kan ikke overskride 60 tegn. Det angitte gruppenavnet er for langt.',
	'GUEST'						=> 'Gjest',
	'GUEST_USERS_ONLINE'		=> 'Det er %d gjester online',
	'GUEST_USERS_TOTAL'			=> '%d gjester',
	'GUEST_USERS_ZERO_ONLINE'	=> 'Det er 0 gjester online',
	'GUEST_USERS_ZERO_TOTAL'	=> '0 gjester',
	'GUEST_USER_ONLINE'			=> 'Det er %d gjest online',
	'GUEST_USER_TOTAL'			=> '%d gjest',
	'G_ADMINISTRATORS'			=> 'Administratorer',
	'G_BOTS'					=> 'Søkeroboter',
	'G_GUESTS'					=> 'Gjester',
	'G_REGISTERED'				=> 'Registrerte brukere',
	'G_REGISTERED_COPPA'		=> 'Registrerte COPPA-brukere',
	'G_GLOBAL_MODERATORS'		=> 'Globale moderatorer',
	'G_NEWLY_REGISTERED'		=> 'Nye brukere',

	'HIDDEN_USERS_ONLINE'			=> '%d skjulte brukere online',
	'HIDDEN_USERS_TOTAL'			=> '%d skjulte',
	'HIDDEN_USERS_TOTAL_AND'		=> '%d skjulte og ',
	'HIDDEN_USERS_ZERO_ONLINE'		=> '0 skjulte brukere online',
	'HIDDEN_USERS_ZERO_TOTAL'		=> '0 skjulte',
	'HIDDEN_USERS_ZERO_TOTAL_AND'	=> '0 skjulte og ',
	'HIDDEN_USER_ONLINE'			=> '%d skjult bruker online',
	'HIDDEN_USER_TOTAL'				=> '%d skjult',
	'HIDDEN_USER_TOTAL_AND'			=> '%d skjult og ',
	'HIDE_GUESTS'					=> 'Skjul gjester',
	'HIDE_ME'						=> 'HSkjul min online status for denne økten',
	'HOURS'							=> 'Timer',
	'HOME'							=> 'Hjem',

	'ICQ'						=> 'ICQ',
	'ICQ_STATUS'				=> 'ICQ-status',
	'IF'						=> 'Hvis',
	'IMAGE'						=> 'Bilde',
	'IMAGE_FILETYPE_INVALID'	=> 'Bildefiltypen %d for mimetype %s er ikke støttet.',
	'IMAGE_FILETYPE_MISMATCH'	=> 'Billedfiltypen passer ikke: Forventet filtype %1$s med filtype %2$s angitt.',
	'IN'						=> 'i',
	'INDEX'						=> 'Hovedside',
	'INFORMATION'				=> 'Informasjon',
	'INTERESTS'					=> 'Interesser',
	'INVALID_DIGEST_CHALLENGE'	=> 'Ugyldig overvåkningsbestilling.',
	'INVALID_EMAIL_LOG'			=> '<strong>%s</strong> er muligens en ugyldig e-post adresse?',
	'IP'						=> 'IP-adresse',
	'IP_BLACKLISTED'			=> 'Din IP-adresse %1$s er blokkert fordi den er svartelistet. For mer informasjon se <a href="%2$s">%2$s</a>.',

	'JABBER'				=> 'Jabber',
	'JOINED'				=> 'Registret',
	'JUMP_PAGE'				=> 'Angi sidenummeret du ønsker å gå til',
	'JUMP_TO'				=> 'Hopp til',
	'JUMP_TO_PAGE'			=> 'Klikk for å hoppe til side…',

	'KB'					=> 'KB',
	'KIB'					=> 'KiB',

	'LAST_POST'							=> 'Siste innlegg',
	'LAST_UPDATED'						=> 'Sist oppdatert',
	'LAST_VISIT'						=> 'Sist besøkt',
	'LDAP_NO_LDAP_EXTENSION'			=> 'LDAP-utvidelsen er ikke tilgjengelig.',
	'LDAP_NO_SERVER_CONNECTION'			=> 'Kunne ikke koble til LDAP-server.',
	'LDAP_SEARCH_FAILED'				=> 'Det oppstod en feil under søking i LDAP-katalogen.',
	'LEGEND'							=> 'Fargeforklaring',
	'LOCATION'							=> 'Bosted',
	'LOCK_POST'							=> 'Lås innlegg',
	'LOCK_POST_EXPLAIN'					=> 'Forhindre redigering',
	'LOCK_TOPIC'						=> 'Lås emne',
	'LOGIN'								=> 'Logg inn',
	'LOGIN_CHECK_PM'					=> 'Logg inn for å sjekke dine private meldinger.',
	'LOGIN_CONFIRMATION'				=> 'Bekreftelse på innlogging',
	'LOGIN_CONFIRM_EXPLAIN'				=> 'For at hindre brute force-hacking av brukerkontoer, må du etter et antall feilaktige innloggingsforsøk, taste inn en bekreftelseskode eller svare på et spørsmål. Koden eller spørsmålet ses under. Hvis du av en eller annen grunn ikke skulle greie å tyde koden, kan du ta kontakt med %sforumets administrator%s.', // unused
	'LOGIN_ERROR_ATTEMPTS'				=> 'Du har overskredet antallet tillatte innloggingsforsøk. Du må derfor i tillegg til ditt brukernavn og passord taste inn en bekreftelseskode eller svare på et spørsmål. Koden eller spørsmålet ses under.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'Du har ikke blitt autentisert av Apache.',
	'LOGIN_ERROR_PASSWORD'				=> 'Du har skrevet inn feil passord. Vennligst kontroller passordet og prøv igjen. Hvis problemet vedvarer, kan du ta kontakt med %sforumets administrator%s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> 'Det var ikke mulig å konvertere ditt passord under oppdatering av dette forumets software. Vennligst forespør %set nytt passord%s. Hvis problemet vedvarer vennligst kontakt %sforumets administrator%s.',
	'LOGIN_ERROR_USERNAME'				=> 'Du har skrevet inn feil brukernavn. Vennligst kontroller brukernavnet og prøv igjen. Hvis problemet vedvarer, kan du ta kontakt med %sforumets administrator%s.',
	'LOGIN_FORUM'						=> 'For å lese og skrive i dette forumet, må du skrive inn forumets passord.',
	'LOGIN_INFO'						=> 'For å kunne logge deg inn, må du være registrert. Registrering tar kun noen få minutter, og gir deg flere muligheter i forumet. I tillegg kan forumets administrator gi registrerte brukere utvidede rettigheter. Før du registrerer deg, må du forsikre deg om at du har satt deg inn i forumets bruksbetingelser og regler. Sørg også for å lese spesielle regler for ulike deler av forumet (om disse eksisterer) før du tar forumet i bruk.',
	'LOGIN_VIEWFORUM'					=> 'The board requires you to be registered and logged in to view this forum.',
	'LOGIN_EXPLAIN_EDIT'				=> 'Du må være innlogget for å ha tilgang til dette forumet.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'Du må være registrert og innlogget for å kunne se hvem som er online.',
	'LOGOUT'							=> 'Logg ut',
	'LOGOUT_USER'						=> 'Logg ut [ %s ]',
	'LOG_ME_IN'							=> 'Logg meg på automatisk ved hvert besøk',

	'MARK'					=> 'Merk',
	'MARK_ALL'				=> 'Merk alle',
	'MARK_FORUMS_READ'		=> 'Merk forumene som lest',
	'MARK_SUBFORUMS_READ'	=> 'Merk underforumene som lest',
	'MB'					=> 'MB',
	'MIB'					=> 'MiB',
	'MCP'					=> 'Moderatorkontrollpanel',
	'MEMBERLIST'			=> 'Medlemmer',
	'MEMBERLIST_EXPLAIN'	=> 'Vis komplett liste over alle forumets medlemmer',
	'MERGE'					=> 'Slå sammen',
	'MERGE_POSTS'			=> 'Flytt innlegg',
	'MERGE_TOPIC'			=> 'Slå sammen emner',
	'MESSAGE'				=> 'Melding',
	'MESSAGES'				=> 'Meldinger',
	'MESSAGE_BODY'			=> 'Meldingsinnhold',
	'MINUTES'				=> 'Minutter',
	'MODERATE'				=> 'Moderer/rediger',
	'MODERATOR'				=> 'Moderator',
	'MODERATORS'			=> 'Moderatorer',
	'MONTH'					=> 'Måned',
	'MOVE'					=> 'Flytt',
	'MSNM'					=> 'MSNM/WLM',

	'NA'						=> 'Ikke tilgjengelig',
	'NEWEST_USER'				=> 'Forumets nyeste medlem <strong>%s</strong>',
	'NEW_MESSAGE'				=> 'Ny melding',
	'NEW_MESSAGES'				=> 'Nye meldinger',
	'NEW_PM'					=> '<strong>%d</strong> ny melding',
	'NEW_PMS'					=> '<strong>%d</strong> nye meldinger',
	'NEW_POST'					=> 'Nytt innlegg',	// Not used anymore
	'NEW_POSTS'					=> 'Nye innlegg',	// Not used anymore
	'NEXT'						=> 'Neste',		// Used in pagination
	'NEXT_STEP'					=> 'Neste',
	'NEVER'						=> 'Aldri',
	'NO'						=> 'Nei',
	'NOT_ALLOWED_MANAGE_GROUP'	=> 'Du har ikke tillatelse til å administrere denne gruppen.',
	'NOT_AUTHORISED'			=> 'Du har ikke adgang til dette område.',
	'NOT_WATCHING_FORUM'		=> 'Du abonnerer ikke lenger på dette forumet.',
	'NOT_WATCHING_TOPIC'		=> 'Du abonnerer ikke lenger på dette emnet.',
	'NOTIFY_ADMIN'				=> 'Vennligst innformer forumets administrator eller webmaster.',
	'NOTIFY_ADMIN_EMAIL'		=> 'Vennligst innformer forumets administrator eller webmaster: <a href="mailto:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> 'Du har ikke tilgang til denne filen.',
	'NO_ACTION'					=> 'Ingen handling spesifisert.',
	'NO_ADMINISTRATORS'			=> 'Det er ingen administratorer.',
	'NO_AUTH_ADMIN'				=> 'Du har ikke administratorrettigheter, og har derfor ikke adgang til administrasjonspanelet.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'Du kan ikke gjenautentisere deg som en annen bruker.',
	'NO_AUTH_OPERATION'			=> 'Du har ikke nødvendige rettigheter for å fullføre denne handlingen.',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'Kunne ikke koble til SMTP-serveren : %1$s : %2$s',
	'NO_BIRTHDAYS'				=> 'Ingen fødselsdager i dag',
	'NO_EMAIL_MESSAGE'			=> 'E-post meldingen var tom.',
	'NO_EMAIL_RESPONSE_CODE'	=> 'Kunne ikke få svarkoder fra e-post serveren.',
	'NO_EMAIL_SUBJECT'			=> 'Du har ikke skrevet noe tittel på e-posten.',
	'NO_FORUM'					=> 'Forumet du har valgt eksisterer ikke.',
	'NO_FORUMS'					=> 'Inneholder ingen forum.',
	'NO_GROUP'					=> 'Brukergruppen du har valgt eksisterer ikke.',
	'NO_GROUP_MEMBERS'			=> 'Denne gruppen har ingen medlemmer.',
	'NO_IPS_DEFINED'			=> 'Ingen IP-adresser eller værtsnavn definert',
	'NO_MEMBERS'				=> 'Ingen medlemmer ble funnet for dette søkekriteriet.',
	'NO_MESSAGES'				=> 'Ingen meldinger',
	'NO_MODE'					=> 'Ingen tilstand angitt.',
	'NO_MODERATORS'				=> 'Det er ingen moderatorers.',
	'NO_NEW_MESSAGES'			=> 'Ingen nye meldinger',
	'NO_NEW_PM'					=> '<strong>0</strong> nye meldinger',
	'NO_NEW_POSTS'				=> 'Ingen nye innlegg',	// Not used anymore
	'NO_ONLINE_USERS'			=> 'Ingen registrerte brukere',
	'NO_POSTS'					=> 'Ingen innlegg',
	'NO_POSTS_TIME_FRAME'		=> 'Ingen innlegg eksisterer i dette emne innenfor for det valgte tidsperioden.',
	'NO_FEED_ENABLED'			=> 'Feeds er ikke tilgjengelige på dette forumet.',
	'NO_FEED'					=> 'Valgte feed er ikke tilgjengelig.',
	'NO_SUBJECT'				=> 'Intet emne er spesifisert',								// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> 'Det spesifiserte søkesystemet eksisterer ikket.',
	'NO_SUPPORTED_AUTH_METHODS'	=> 'Ingen støttede autentiseringsmetoder.',
	'NO_TOPIC'					=> 'Det valgte emne finnes ikke.',
	'NO_TOPIC_FORUM'			=> 'Emnet eller forumet eksisterer ike lenger.',
	'NO_TOPICS'					=> 'Det er ingen emner eller innlegg i dette forumet.',
	'NO_TOPICS_TIME_FRAME'		=> 'Ingen emner eksisterer i dette forum for den valgte tidsperioden.',
	'NO_UNREAD_PM'				=> '<strong>0</strong> uleste meldinger',
	'NO_UNREAD_POSTS'			=> 'Ingen uleste innlegg',
	'NO_UPLOAD_FORM_FOUND'		=> 'Opplastning iverksatt, men ingen gyldig filopplastningsform funnet.',
	'NO_USER'					=> 'Den valgte brukeren eksisterer ikke.',
	'NO_USERS'					=> 'De valgte brukerne eksisterer ikke.',
	'NO_USER_SPECIFIED'			=> 'Ingen brukernavn spesifisert.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> 'Ingen innlegg i kø',		// 0
		1			=> '1 innlegg i kø',		// 1
		2			=> '%d innlegg i kø',		// 2+
	),

	'OCCUPATION'				=> 'Yrke',
	'OFFLINE'					=> 'Offline',
	'ONLINE'					=> 'Online',
	'ONLINE_BUDDIES'			=> 'Online venner',
	'ONLINE_USERS_TOTAL'		=> 'Det er totalt <strong>%d</strong> brukere pålogget :: ',
	'ONLINE_USERS_ZERO_TOTAL'	=> 'Det er <strong>0</strong> brukere pålogget :: ',
	'ONLINE_USER_TOTAL'			=> 'Det er <strong>%d</strong> bruker pålogget :: ',
	'OPTIONS'					=> 'Valg',

	'PAGE_OF'				=> 'Side <strong>%1$d</strong> av <strong>%2$d</strong>',
	'PASSWORD'				=> 'Passord',
	'PIXEL'					=> 'px',
	'PLAY_QUICKTIME_FILE'	=> 'Spill Quicktime-fil',
	'PM'					=> 'PM',
	'PM_REPORTED'			=> 'Klikk for å se rapport',
	'POSTING_MESSAGE'		=> 'Skriver et innlegg  %s',
	'POSTING_PRIVATE_MESSAGE'	=> 'Skriver en privat melding',
	'POST'					=> 'innlegg',
	'POST_ANNOUNCEMENT'		=> 'Annonsering',
	'POST_STICKY'			=> 'Prioritet/Oppslag',
	'POSTED'				=> 'Skrevet',
	'POSTED_IN_FORUM'		=> 'i',
	'POSTED_ON_DATE'		=> 'den',
	'POSTS'					=> 'Innlegg',
	'POSTS_UNAPPROVED'		=> 'Minst ett innlegg i dette emnet er ikke godkjent .',
	'POST_BY_AUTHOR'		=> 'av',
	'POST_BY_FOE'			=> 'Dette innlegget er skrevet av <strong>%1$s</strong> som er i din ignoreringsliste, og er derfor skjult. %2$sVis innlegg%3$s.',
	'POST_DAY'				=> '%.2f innlegg pr dag',
	'POST_DETAILS'			=> 'Innleggsdetaljer',
	'POST_NEW_TOPIC'		=> 'Opprett et nytt emne',
	'POST_PCT'				=> '%.2f%% av alle innlegg',
	'POST_PCT_ACTIVE'		=> '%.2f%% av alle brukeres innlegg',
	'POST_PCT_ACTIVE_OWN'	=> '%.2f%% av dine innlegg',
	'POST_REPLY'			=> 'Skriv et svar',
	'POST_REPORTED'			=> 'Klikk for å se rapporten',
	'POST_SUBJECT'			=> 'Innleggets tittel',
	'POST_TIME'				=> 'Skrevet',
	'POST_TOPIC'			=> 'Skriv et nytt emne',
	'POST_UNAPPROVED'		=> 'Dette innlegget venter på godkjenning',
	'PREVIEW'				=> 'Forhåndsvis',
	'PREVIOUS'				=> 'Forrige',		// Used in pagination
	'PREVIOUS_STEP'			=> 'Forrige',
	'PRIVACY'				=> 'Personvern',
	'PRIVATE_MESSAGE'		=> 'Privat melding',
	'PRIVATE_MESSAGES'		=> 'Private meldinger',
	'PRIVATE_MESSAGING'		=> 'Privat meldingstjenesten',
	'PROFILE'				=> 'Brukerkontrollpanel',

	'READING_FORUM'				=> 'Leser emner i %s',
	'READING_GLOBAL_ANNOUNCE'	=> 'Leser global annonsering',
	'READING_LINK'				=> 'Følger forumlink %s',
	'READING_TOPIC'				=> 'Leser et emne i %s',
	'READ_PROFILE'				=> 'Profil',
	'REASON'					=> 'Begrunnelse',
	'RECORD_ONLINE_USERS'		=> 'Høyest antall samtidige brukere på forumet var <strong>%1$s</strong> Dette skjedde %2$s',
	'REDIRECT'					=> 'Videresend',
	'REDIRECTS'					=> 'Videresendelser',
	'REGISTER'					=> 'Registrer deg',
	'REGISTERED_USERS'			=> 'Registrerte brukere:',
	'REG_USERS_ONLINE'			=> 'Det er %d registrerte brukere og ',
	'REG_USERS_TOTAL'			=> '%d registrerte, ',
	'REG_USERS_TOTAL_AND'		=> '%d registrerte og ',
	'REG_USERS_ZERO_ONLINE'		=> 'det er 0 registrerte brukere og ',
	'REG_USERS_ZERO_TOTAL'		=> '0 registrerte, ',
	'REG_USERS_ZERO_TOTAL_AND'	=> '0 registrerte og ',
	'REG_USER_ONLINE'			=> 'Det er %d registrert bruker og ',
	'REG_USER_TOTAL'			=> '%d registrert, ',
	'REG_USER_TOTAL_AND'		=> '%d registrert og ',
	'REMOVE'					=> 'Fjern',
	'REMOVE_INSTALL'			=> 'Vennligst slett, flytt eller endre navn på mappen <strong>install</strong> før du går online med forumet. Så lenge denne mappen finnes er kun administratorkontrollpanelet (ACP) tilgjengelig.',
	'REPLIES'					=> 'Svar',
	'REPLY_WITH_QUOTE'			=> 'Svar med sitat',
	'REPLYING_GLOBAL_ANNOUNCE'	=> 'Svarer på global annonsering',
	'REPLYING_MESSAGE'			=> 'Svarer på melding i %s',
	'REPORT_BY'					=> 'Rapport av',
	'REPORT_POST'				=> 'Rapporter dette innlegget',
	'REPORTING_POST'			=> 'Rapporterer et innlegg',
	'RESEND_ACTIVATION'			=> 'Send aktiverings e-post på nytt',
	'RESET'						=> 'Nullstill',
	'RESTORE_PERMISSIONS'		=> 'Gjennopprett rettigheter',
	'RETURN_INDEX'				=> '%sTilbake til hovedsiden%s',
	'RETURN_FORUM'				=> '%sTilbake til det sist besøkte forumet%s',
	'RETURN_PAGE'				=> '%sTilbake til forrige side%s',
	'RETURN_TOPIC'				=> '%sTilbake til det sist besøkte emnet%s',
	'RETURN_TO'					=> 'Tilbake til',
	'FEED'						=> 'Feed',
	'FEED_NEWS'					=> 'nyheter',
	'FEED_TOPICS_ACTIVE'		=> 'Aktive emner',
	'FEED_TOPICS_NEW'			=> 'Nye emner',
	'RULES_ATTACH_CAN'			=> 'Du <strong>kan</strong> laste opp vedlegg til dette forumet',
	'RULES_ATTACH_CANNOT'		=> 'Du <strong>kan ikke</strong> laste opp vedlegg til dette forumet',
	'RULES_DELETE_CAN'			=> 'Du <strong>kan</strong> slette dine egne innlegg i dette forumet',
	'RULES_DELETE_CANNOT'		=> 'Du <strong>kan ikket</strong> slette dine egne innlegg i dette forumet',
	'RULES_DOWNLOAD_CAN'		=> 'Du <strong>kan</strong> laste ned vedlegg fra dette forumet',
	'RULES_DOWNLOAD_CANNOT'		=> 'Du <strong>kan ikke</strong> laste ned vedlegg fra dette forumet',
	'RULES_EDIT_CAN'			=> 'Du <strong>kan</strong> redigere dine egne innlegg i dette forumet',
	'RULES_EDIT_CANNOT'			=> 'Du <strong>kan ikke</strong> redigere dine egne innlegg i dette forumet',
	'RULES_LOCK_CAN'			=> 'Du <strong>kan</strong> låse dine egne emner i dette forumet',
	'RULES_LOCK_CANNOT'			=> 'Du <strong>kan ikke</strong> låse dine egne emner i dette forumet',
	'RULES_POST_CAN'			=> 'Du <strong>kan</strong> opprette nye emner i dette forumet',
	'RULES_POST_CANNOT'			=> 'Du <strong>kan ikke</strong> opprette nye emner i dette forumet',
	'RULES_REPLY_CAN'			=> 'Du <strong>kan</strong> svare på emner i dette forumet',
	'RULES_REPLY_CANNOT'		=> 'Du <strong>kan ikke</strong> svare på emner i dette forumet',
	'RULES_VOTE_CAN'			=> 'Du <strong>kan</strong> stemme i avstemninger i dette forumet',
	'RULES_VOTE_CANNOT'			=> 'Du <strong>kan ikke</strong> stemme i avstemninger i dette forumet',

	'SEARCH'					=> 'Søk',
	'SEARCH_MINI'				=> 'Søk…',
	'SEARCH_ADV'				=> 'Avansert søk',
	'SEARCH_ADV_EXPLAIN'		=> 'Vis de avanserte søkevalgene',
	'SEARCH_KEYWORDS'			=> 'Søk etter nøkkelord',
	'SEARCHING_FORUMS'			=> 'Søker i forumene',
	'SEARCH_ACTIVE_TOPICS'		=> 'Vis aktive emner',
	'SEARCH_FOR'				=> 'Søk etter',
	'SEARCH_FORUM'				=> 'Søk i dette forumet…',
	'SEARCH_NEW'				=> 'Vis nye innlegg',
	'SEARCH_POSTS_BY'			=> 'Søk innlegg skrevet av',
	'SEARCH_SELF'				=> 'Vis dine innlegg',
	'SEARCH_TOPIC'				=> 'Søk i dette emnet…',
	'SEARCH_UNANSWERED'			=> 'Vis ubesvarte innlegg',
	'SEARCH_UNREAD'				=> 'Vis uleste innlegg',
	'SEARCH_USER_POSTS'			=> 'Søk i brukerens innlegg',
	'SECONDS'					=> 'Sekunder',
	'SELECT'					=> 'velg',
	'SELECT_ALL_CODE'			=> 'Velg alt',
	'SELECT_DESTINATION_FORUM'	=> 'Vennligst velg destinasjonsforum',
	'SELECT_FORUM'				=> 'Velg et forum',
	'SEND_EMAIL'				=> 'Send e-post',				// Used for submit buttons
	'SEND_EMAIL_USER'			=> 'E-post',				// Used as: {L_SEND_EMAIL_USER} {USERNAME} -> E-mail UserX
	'SEND_PRIVATE_MESSAGE'		=> 'Send en privat melding',
	'SETTINGS'					=> 'Innstillinger',
	'SIGNATURE'					=> 'Signatur',
	'SKIP'						=> 'Hopp til innhold',
	'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP serveren støtter ikke autentisering.',
	'SORRY_AUTH_READ'			=> 'Du har ikke rettigheter til å lese i dette forumet.',
	'SORRY_AUTH_VIEW_ATTACH'	=> 'Du har ikke rettigheter til å laste ned dette vedlegget.',
	'SORT_BY'					=> 'Sorter etter',
	'SORT_JOINED'				=> 'Registreringsdato',
	'SORT_LOCATION'				=> 'Bosted',
	'SORT_RANK'					=> 'Rang',
	'SORT_POSTS'				=> 'Innlegg',
	'SORT_TOPIC_TITLE'			=> 'Emnetittel',
	'SORT_USERNAME'				=> 'Brukernavn',
	'SPLIT_TOPIC'				=> 'Splitt emne',
	'SQL_ERROR_OCCURRED'		=> 'Det oppstod en SQL-feil ved lesing av denne siden. Vennligst kontakt %sadministrator%s hvis problemet vedvarer.',
	'STATISTICS'				=> 'Statistikker',
	'START_WATCHING_FORUM'		=> 'Abonner på forumet',
	'START_WATCHING_TOPIC'		=> 'Abonner på emne',
	'STOP_WATCHING_FORUM'		=> 'Stopp abonnementet på forumet',
	'STOP_WATCHING_TOPIC'		=> 'Stopp abonnementet på emnet',
	'SUBFORUM'					=> 'Underforum',
	'SUBFORUMS'					=> 'Underforum',
	'SUBJECT'					=> 'Emne',
	'SUBMIT'					=> 'Utfør',

	'TERMS_USE'			=> 'Betingelser for bruk',
	'TEST_CONNECTION'	=> 'Test tilkobling',
	'THE_TEAM'			=> 'Forumledelse',
	'TIME'				=> 'Tid',
	
	'TOO_LARGE'						=> 'Den angitte verdien er for stor.',
	'TOO_LARGE_MAX_RECIPIENTS'		=> 'Verdien av <strong>Maksimalt antall mottagere av en privat melding</strong> er for høy.',

	'TOO_LONG'						=> 'Den angitte verdien er for lang.',

	'TOO_LONG_AIM'					=> 'Det angitte skjermnavnet er for langt.',
	'TOO_LONG_CONFIRM_CODE'			=> 'Bekreftelseskoden du skrev inn er for lang.',
	'TOO_LONG_DATEFORMAT'			=> 'Dato formatet du skrev inn er for langt.',
	'TOO_LONG_ICQ'					=> 'ICQ-nummeret du skrev inn er for langt.',
	'TOO_LONG_INTERESTS'			=> 'Interesseinformasjonen du skrev inn er for lang.',
	'TOO_LONG_JABBER'				=> 'Jabber-brukernavnet du skrev inn er for langt.',
	'TOO_LONG_LOCATION'				=> 'Bostedet du skrev inn er for langt.',
	'TOO_LONG_MSN'					=> 'MSNM/WLM navnet du skrev inn er for langt.',
	'TOO_LONG_NEW_PASSWORD'			=> 'Passordet du skrev inn er for langt.',
	'TOO_LONG_OCCUPATION'			=> 'Yrket du skrev inn er for langt.',
	'TOO_LONG_PASSWORD_CONFIRM'		=> 'Passordbekreftelsen du skrev inn er for lang.',
	'TOO_LONG_USER_PASSWORD'		=> 'Passordet du skrev inn er for langt.',
	'TOO_LONG_USERNAME'				=> 'Brukernavnet du skrev inn er for langt.',
	'TOO_LONG_EMAIL'				=> 'E-postadressen du skrev inn er for lang.',
	'TOO_LONG_EMAIL_CONFIRM'		=> 'E-postadressebekreftelsen du skrev inn er for lang.',
	'TOO_LONG_WEBSITE'				=> 'Nettadressen du skrev inn er for lang.',
	'TOO_LONG_YIM'					=> 'Yahoo-brukernavnet du skrev inn er for langt.',

	'TOO_MANY_VOTE_OPTIONS'			=> 'Du har forsøkt å stemme på for mange valg.',

	'TOO_SHORT'						=> 'Den angitte verdien er for kort.',

	'TOO_SHORT_AIM'					=> 'Det angitte skjermnavnet er for kort.',
	'TOO_SHORT_CONFIRM_CODE'		=> 'Bekreftelseskoden du skrev inn er for kort.',
	'TOO_SHORT_DATEFORMAT'			=> 'Dato formatet du skrev inn er for kort.',
	'TOO_SHORT_ICQ'					=> 'ICQ-nummeret du skrev inn er for kort.',
	'TOO_SHORT_INTERESTS'			=> 'Interesseinformasjonen du skrev inn er for kort.',
	'TOO_SHORT_JABBER'				=> 'Jabber-brukernavnet du skrev inn er for kort.',
	'TOO_SHORT_LOCATION'			=> 'Bostedet du skrev inn er for kort.',
	'TOO_SHORT_MSN'					=> 'MSNM/WLM navnet du skrev inn er for kort.',
	'TOO_SHORT_NEW_PASSWORD'		=> 'Passordet du skrev inn er for kort.',
	'TOO_SHORT_OCCUPATION'			=> 'Yrket du skrev inn er for kort.',
	'TOO_SHORT_PASSWORD_CONFIRM'	=> 'Passordbekreftelsen du skrev inn er for kort.',
	'TOO_SHORT_USER_PASSWORD'		=> 'Passordet du skrev inn er for kort.',
	'TOO_SHORT_USERNAME'			=> 'Brukernavnet du skrev inn er for kort.',
	'TOO_SHORT_EMAIL'				=> 'E-postadressen du skrev inn er for kort.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> 'E-postadressebekreftelsen du skrev inn er for kort.',
	'TOO_SHORT_WEBSITE'				=> 'Nettadressen du skrev inn er for kort.',
	'TOO_SHORT_YIM'					=> 'Yahoo-brukernavnet du skrev inn er for kort.',
	
	'TOO_SMALL'						=> 'Den angitte verdien er for liten.',
	'TOO_SMALL_MAX_RECIPIENTS'		=> 'Verdien av <strong>Maksimalt antall mottagere av en privat melding</strong> er for liten.',

	'TOPIC'				=> 'Emne',
	'TOPICS'			=> 'Emner',
	'TOPICS_UNAPPROVED'	=> 'Minst et emne i forumet er ikke godkjent.',
	'TOPIC_ICON'		=> 'Emneikon',
	'TOPIC_LOCKED'		=> 'Dette emnet er stengt, du kan ikke redigere eller legge inn nye innlegg.',
	'TOPIC_LOCKED_SHORT'=> 'Emnet er stengt',
	'TOPIC_MOVED'		=> 'Flyttet emne',
	'TOPIC_REVIEW'		=> 'Emnegjennomgang',
	'TOPIC_TITLE'		=> 'Emnetittel',
	'TOPIC_UNAPPROVED'	=> 'Dette emnet er ikke godkjent',
	'TOTAL_ATTACHMENTS'	=> 'Vedlegg',
	'TOTAL_LOG'			=> '1 logg',
	'TOTAL_LOGS'		=> '%d logger',
	'TOTAL_NO_PM'		=> '0 private meldinger totalt',
	'TOTAL_PM'			=> '1 privat melding totalt',
	'TOTAL_PMS'			=> '%d private meldinger totalt',
	'TOTAL_POSTS'		=> 'Antall innlegg',
	'TOTAL_POSTS_OTHER'	=> 'Antall innlegg <strong>%d</strong>',
	'TOTAL_POSTS_ZERO'	=> 'Antall innlegg <strong>0</strong>',
	'TOPIC_REPORTED'	=> 'Dette emnet har blitt rapportert',
	'TOTAL_TOPICS_OTHER'=> 'Antall emner <strong>%d</strong>',
	'TOTAL_TOPICS_ZERO'	=> 'Antall emner <strong>0</strong>',
	'TOTAL_USERS_OTHER'	=> 'Antall medlemmer <strong>%d</strong>',
	'TOTAL_USERS_ZERO'	=> 'Antall medlemmer <strong>0</strong>',
	'TRACKED_PHP_ERROR'	=> 'Sporede PHP-feil: %s',

	'UNABLE_GET_IMAGE_SIZE'	=> 'Det var ikke mulig å fastslå bildets dimensjoner.',
	'UNABLE_TO_DELIVER_FILE'=> 'Kunne ikke levere fil.',
	'UNKNOWN_BROWSER'		=> 'Ukjent nettleser',
	'UNMARK_ALL'			=> 'Fjern alle markeringer',
	'UNREAD_MESSAGES'		=> 'Uleste meldinger',
	'UNREAD_PM'				=> '<strong>%d</strong> ulest melding',
	'UNREAD_PMS'			=> '<strong>%d</strong> uleste meldinger',
	'UNREAD_POST'			=> 'Ulest innlegg',
	'UNREAD_POSTS'			=> 'Uleste innlegg',
	'UNWATCHED_FORUMS'			=> 'Du abonnerer ikke lenger på de valgte forumene',
	'UNWATCHED_TOPICS'			=> 'Du abonnerer ikke lenger på de valgte emnene.',
	'UNWATCHED_FORUMS_TOPICS'	=> 'Du abonnerer ikke lenger på de valgte forum og emner.',
	'UPDATE'				=> 'Oppdater',
	'UPLOAD_IN_PROGRESS'	=> 'Opplastingen er i gang.',
	'URL_REDIRECT'			=> 'Hvis nettleseren ikke støtter meta-videresending, kan du klikke %sher%s for å bli videresendt.',
	'USERGROUPS'			=> 'Grupper',
	'USERNAME'				=> 'Brukernavn',
	'USERNAMES'				=> 'Brukernavn',
	'USER_AVATAR'			=> 'Brukerens avatar',
	'USER_CANNOT_READ'		=> 'Du kan ikke lese innlegg i dette forumet.',
	'USER_POST'				=> '%d Innlegg',
	'USER_POSTS'			=> '%d Innlegg',
	'USERS'					=> 'Brukere',
	'USE_PERMISSIONS'		=> 'Test ut brukernes rettigheter',

	'USER_NEW_PERMISSION_DISALLOWED'	=> 'Vi beklager, men du kan ikke bruke denne muligheten. For at anvende den må du være registrert og delta mere aktivt.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'					=> 'Lest',
	'VIEWING_FAQ'				=> 'Leser OSS',
	'VIEWING_MEMBERS'			=> 'Ser på medlemsdetaljer',
	'VIEWING_ONLINE'			=> 'Ser på listen over påloggede brukere',
	'VIEWING_MCP'				=> 'Ser på moderatorkontrollpanelet',
	'VIEWING_MEMBER_PROFILE'	=> 'Ser på en medlemsprofil',
	'VIEWING_PRIVATE_MESSAGES'	=> 'Leser private meldinger',
	'VIEWING_REGISTER'			=> 'Registrerer seg',
	'VIEWING_UCP'				=> 'Ser på brukerkontrollpanelet',
	'VIEWS'						=> 'Visninger',
	'VIEW_BOOKMARKS'			=> 'Vis bokmerker',
	'VIEW_FORUM_LOGS'			=> 'Vis logger',
	'VIEW_LATEST_POST'			=> 'Vis siste innlegg',
	'VIEW_NEWEST_POST'			=> 'Vis nyeste uleste innlegg',
	'VIEW_NOTES'				=> 'Se brukernotater',
	'VIEW_ONLINE_TIME'			=> 'basert på aktive brukere det siste %d minuttet',
	'VIEW_ONLINE_TIMES'			=> 'basert på aktive brukere de siste %d minuttene',
	'VIEW_TOPIC'				=> 'vis emne',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'Annonsering: ',
	'VIEW_TOPIC_GLOBAL'			=> 'Global annonsering: ',
	'VIEW_TOPIC_LOCKED'			=> 'låst: ',
	'VIEW_TOPIC_LOGS'			=> 'Vis logger',
	'VIEW_TOPIC_MOVED'			=> 'Flyttet: ',
	'VIEW_TOPIC_POLL'			=> 'Avstemning: ',
	'VIEW_TOPIC_STICKY'			=> 'Prioritet: ',
	'VISIT_WEBSITE'				=> 'Besøk hjemmeside',

	'WARNINGS'			=> 'Advarsler',
	'WARN_USER'			=> 'Advar brukeren',
	'WELCOME_SUBJECT'	=> 'Velkommen til %s',
	'WEBSITE'			=> 'Hjemmeside',
	'WHOIS'				=> 'Whois',
	'WHO_IS_ONLINE'		=> 'Hvem er online',
	'WRONG_PASSWORD'	=> 'Passordet er ikke gyldig.',

	'WRONG_DATA_ICQ'			=> 'Nummeret du oppgav er ikke et gyldig ICQ-nummer.',
	'WRONG_DATA_JABBER'			=> 'Navnet du skrev er ikke et gyldig Jabber-brukernavn.',
	'WRONG_DATA_LANG'			=> 'Språket du spesifiserte er ikke gyldig.',
	'WRONG_DATA_WEBSITE'		=> 'Adressen på hjemmesiden må være en gyldig URL, inkluder protokoll. For eksempel http://www.eksempel.com/.',
	'WROTE'						=> 'skrev',

	'YEAR'				=> 'År',
	'YEAR_MONTH_DAY'	=> '(YYYY-MM-DD)',
	'YES'				=> 'Ja',
	'YIM'				=> 'YIM',
	'YOU_LAST_VISIT'	=> 'Siste besøk var: %s',
	'YOU_NEW_PM'		=> 'En ny privat melding venter på deg i innboksen.',
	'YOU_NEW_PMS'		=> 'Nye private meldinger venter på deg i innboksen.',
	'YOU_NO_NEW_PM'		=> 'Ingen nye private meldinger.',

	'datetime'			=> array(
		'TODAY'		=> 'I dag',
		'TOMORROW'	=> 'I morgen',
		'YESTERDAY'	=> 'I går',
		'AGO'		=> array(
			0		=> 'mindre enn ett minutt siden',
			1		=> '%d minutt siden',
			2		=> '%d minutter siden',
			60		=> '1 time siden',
		),

		'Sunday'	=> 'søndag',
		'Monday'	=> 'mandag',
		'Tuesday'	=> 'tirsdag',
		'Wednesday'	=> 'onsdag',
		'Thursday'	=> 'torsdag',
		'Friday'	=> 'fredag',
		'Saturday'	=> 'lørdag',

		'Sun'		=> 'søn',
		'Mon'		=> 'man',
		'Tue'		=> 'tirs',
		'Wed'		=> 'ons',
		'Thu'		=> 'tors',
		'Fri'		=> 'fre',
		'Sat'		=> 'lør',

		'January'	=> 'januar',
		'February'	=> 'februar',
		'March'		=> 'mars',
		'April'		=> 'april',
		'May'		=> 'mai',
		'June'		=> 'juni',
		'July'		=> 'juli',
		'August'	=> 'august',
		'September' => 'september',
		'October'	=> 'oktober',
		'November'	=> 'november',
		'December'	=> 'desember',

		'Jan'		=> 'jan',
		'Feb'		=> 'feb',
		'Mar'		=> 'mar',
		'Apr'		=> 'apr',
		'May_short'	=> 'mai',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> 'jun',
		'Jul'		=> 'jul',
		'Aug'		=> 'aug',
		'Sep'		=> 'sep',
		'Oct'		=> 'okt',
		'Nov'		=> 'nov',
		'Dec'		=> 'des',
	),

	'tz'				=> array(
		'-12'	=> 'UTC - 12 timer',
		'-11'	=> 'UTC - 11 timer',
		'-10'	=> 'UTC - 10 timer',
		'-9.5'	=> 'UTC - 9:30 timer',
		'-9'	=> 'UTC - 9 timer',
		'-8'	=> 'UTC - 8 timer',
		'-7'	=> 'UTC - 7 timer',
		'-6'	=> 'UTC - 6 timer',
		'-5'	=> 'UTC - 5 timer',
		'-4.5'	=> 'UTC - 4:30 timer',
		'-4'	=> 'UTC - 4 timer',
		'-3.5'	=> 'UTC - 3:30 timer',
		'-3'	=> 'UTC - 3 timer',
		'-2'	=> 'UTC - 2 timer',
		'-1'	=> 'UTC - 1 time',
		'0'		=> 'UTC',
		'1'		=> 'UTC + 1 time',
		'2'		=> 'UTC + 2 timer',
		'3'		=> 'UTC + 3 timer',
		'3.5'	=> 'UTC + 3:30 timer',
		'4'		=> 'UTC + 4 timer',
		'4.5'	=> 'UTC + 4:30 timer',
		'5'		=> 'UTC + 5 timer',
		'5.5'	=> 'UTC + 5:30 timer',
		'5.75'	=> 'UTC + 5:45 timer',
		'6'		=> 'UTC + 6 timer',
		'6.5'	=> 'UTC + 6:30 timer',
		'7'		=> 'UTC + 7 timer',
		'8'		=> 'UTC + 8 timer',
		'8.75'	=> 'UTC + 8:45 timer',
		'9'		=> 'UTC + 9 timer',
		'9.5'	=> 'UTC + 9:30 timer',
		'10'	=> 'UTC + 10 timer',
		'10.5'	=> 'UTC + 10:30 timer',
		'11'	=> 'UTC + 11 timer',
		'11.5'	=> 'UTC + 11:30 timer',
		'12'	=> 'UTC + 12 timer',
		'12.75'	=> 'UTC + 12:45 timer',
		'13'	=> 'UTC + 13 timer',
		'14'	=> 'UTC + 14 timer',
		'dst'	=> '[ <abbr title="Sommertid">DST</abbr> ]',
	),

	'tz_zones'	=> array(
		'-12'	=> '[UTC - 12] Baker Island Time',
		'-11'	=> '[UTC - 11] Niue Time, Samoa Standard Time',
		'-10'	=> '[UTC - 10] Hawaii-Aleutian Standard Time, Cook Island Time',
		'-9.5'	=> '[UTC - 9:30] Marquesas Islands Time',
		'-9'	=> '[UTC - 9] Alaska Standard Time, Gambier Island Time',
		'-8'	=> '[UTC - 8] Pacific Standard Time',
		'-7'	=> '[UTC - 7] Mountain Standard Time',
		'-6'	=> '[UTC - 6] Central Standard Time',
		'-5'	=> '[UTC - 5] Eastern Standard Time',
		'-4.5'	=> '[UTC - 4:30] Venezuelan Standard Time',
		'-4'	=> '[UTC - 4] Atlantic Standard Time',
		'-3.5'	=> '[UTC - 3:30] Newfoundland Standard Time',
		'-3'	=> '[UTC - 3] Amazon Standard Time, Central Greenland Time',
		'-2'	=> '[UTC - 2] Fernando de Noronha Time, South Georgia &amp; the South Sandwich Islands Time',
		'-1'	=> '[UTC - 1] Azores Standard Time, Cape Verde Time, Eastern Greenland Time',
		'0'		=> '[UTC] Western European Time, Greenwich Mean Time',
		'1'		=> '[UTC + 1] Central European Time, West African Time',
		'2'		=> '[UTC + 2] Eastern European Time, Central African Time',
		'3'		=> '[UTC + 3] Moscow Standard Time, Eastern African Time',
		'3.5'	=> '[UTC + 3:30] Iran Standard Time',
		'4'		=> '[UTC + 4] Gulf Standard Time, Samara Standard Time',
		'4.5'	=> '[UTC + 4:30] Afghanistan Time',
		'5'		=> '[UTC + 5] Pakistan Standard Time, Yekaterinburg Standard Time',
		'5.5'	=> '[UTC + 5:30] Indian Standard Time, Sri Lanka Time',
		'5.75'	=> '[UTC + 5:45] Nepal Time',
		'6'		=> '[UTC + 6] Bangladesh Time, Bhutan Time, Novosibirsk Standard Time',
		'6.5'	=> '[UTC + 6:30] Cocos Islands Time, Myanmar Time',
		'7'		=> '[UTC + 7] Indochina Time, Krasnoyarsk Standard Time',
		'8'		=> '[UTC + 8] Chinese Standard Time, Australian Western Standard Time, Irkutsk Standard Time',
		'8.75'	=> '[UTC + 8:45] Southeastern Western Australia Standard Time',
		'9'		=> '[UTC + 9] Japan Standard Time, Korea Standard Time, Chita Standard Time',
		'9.5'	=> '[UTC + 9:30] Australian Central Standard Time',
		'10'	=> '[UTC + 10] Australian Eastern Standard Time, Vladivostok Standard Time',
		'10.5'	=> '[UTC + 10:30] Lord Howe Standard Time',
		'11'	=> '[UTC + 11] Solomon Island Time, Magadan Standard Time',
		'11.5'	=> '[UTC + 11:30] Norfolk Island Time',
		'12'	=> '[UTC + 12] New Zealand Time, Fiji Time, Kamchatka Standard Time',
		'12.75'	=> '[UTC + 12:45] Chatham Islands Time',
		'13'	=> '[UTC + 13] Tonga Time, Phoenix Islands Time',
		'14'	=> '[UTC + 14] Line Island Time',
	),

	// The value is only an example and will get replaced by the current time on view
	'dateformats'	=> array(
		'D d. M Y H:i'			=> 'man 01. jan 2007 13:37',
		'd M Y, H:i'			=> '01 jan 2007, 13:37',
		'd M Y H:i'				=> '01 jan 2007 13:37',
		'M jS, \'y, H:i'		=> 'jan 1st, \'07, 13:37',
		'D M d, Y g:i a'		=> 'mon jan 01, 2007 1:37 pm',
		'F jS, Y, g:i a'		=> 'januar 1st, 2007, 1:37 pm',
		'|d M Y|, H:i'			=> 'I dag, 13:37 / 01 jan 2007, 13:37',
		'|F jS, Y|, g:i a'		=> 'I dag, 1:37 pm / january 1st, 2007, 1:37 pm'
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'D d. M Y H:i', // man 01. jan 2007 13:37

));

?>